# Gradle Performance Settings
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.caching.debug=false
org.gradle.configureondemand=false

#----------Mod Properties----------#
#Make sure you edit these before running renameExampleMod!
mod.version=1.1.26
mod.license=MIT
# Root Folder Path (/java/group/namespace/)
mod.group=rique
mod.namespace=notick
# Mod ID and Main Class Name
mod.id=no_ticks
mod.name=NoTick
# English Display Info
mod.author=Rique
mod.github=https://github.com/Riqqqque/NoTick-Rique
mod.display_name=NoTick
mod.description=Skips ticking for distant unseen entities while preserving gameplay with claims and whitelist controls
mod.discord=https://discord.gg/3kxRQHg4AQ
#----------------------------------#


#------------ Misc Info -----------#
client.user=Rique
client.uuid=
client.modrinth_profiles_dir=
#----------------------------------#


#---------Publishing Info----------#
publish.modrinth=JNQBF5dH
publish.curseforge=0
publish.maven_url=example.invalid
publish.use_snapshot_maven=false
#----------------------------------#


#----------Dependencies------------#
deps.minecraft=[VERSIONED]
deps.fapi=[VERSIONED]
deps.yarn_build=[VERSIONED]
deps.yacl=[VERSIONED]
deps.cloth=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fml=[VERSIONED]
mod.mc_dep=[VERSIONED]
mod.mc_title=[VERSIONED]
mod.mc_targets=[VERSIONED]
deps.forgeconfigapi=[VERSIONED]
