modLoader = "javafml"
loaderVersion="[1,)"
license="${license}"
showAsResourcePack=false

issueTrackerURL = "${github}/issues"

[[mods]]
modId="${id}"
version="${modversion}"
displayName="${display_name}"
authors="${author}"
description="${description}"
logoFile="assets/${namespace}/textures/mod_logo.png"
displayURL = "${github}"

[[mixins]]
config = "mixins.${mixinid}.json"

[[dependencies."${id}"]]
modId="minecraft"
mandatory=true
versionRange="${mc}"
ordering="NONE"
side="BOTH"
